name: Deploy Backend and Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}


    - name: Deploy Backend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-15-222-12-208.ca-central-1.compute.amazonaws.com  << 'EOF'
          cd ~/my-commerce/my-spring
          bash deploy.sh
        EOF