name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner used for this job

    env:
      EC2_SSH_KEY: |
        ${{ secrets.EC2_SSH_KEY }}  # Multiline secret for the private key

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH Agent
      run: |
        echo "${EC2_SSH_KEY}" > ssh_key.pem
        chmod 600 ssh_key.pem
        eval "$(ssh-agent -s)"
        ssh-add ssh_key.pem

    - name: Deploy Backend to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/my-commerce/my-spring
          bash deploy.sh
        EOF
